export const PLANS={free:{price:0,radars:50,interval:600,scans:1000000},starter:{price:0,radars:50,interval:600,scans:1000000},pro:{price:0,radars:50,interval:600,scans:1000000},growth:{price:0,radars:50,interval:600,scans:1000000}} as const;
export type Plan=keyof typeof PLANS;
export function entitlement(_s?:{plan:string;status:string;current_period_end?:string|Date|null}){return "free" as Plan;}
export type Schedule={days:number[];start:string;end:string}|null;
export function inSchedule(date:Date,timezone:string,schedule:Schedule){if(!schedule)return true;const p=new Intl.DateTimeFormat("en-US",{timeZone:timezone,weekday:"short",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date);const value=(t:string)=>p.find(v=>v.type===t)!.value;const day=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(value("weekday"));const time=value("hour")+":"+value("minute");if(schedule.start===schedule.end)return schedule.days.includes(day);if(schedule.start<schedule.end)return schedule.days.includes(day)&&time>=schedule.start&&time<schedule.end;return(schedule.days.includes(day)&&time>=schedule.start)||(schedule.days.includes((day+6)%7)&&time<schedule.end);}
export function validateQuery(query:string){if(query.trim().length<2||query.length>512)throw new Error("Use a query between 2 and 512 characters.");const quotes=query.split('"').length-1;if(quotes%2)throw new Error("Close the quotation marks in your query.");let depth=0;for(const c of query){if(c==="(")depth++;if(c===")"&&--depth<0)throw new Error("Check the parentheses in your query.");}if(depth)throw new Error("Check the parentheses in your query.");return query.trim();}
export type SocialPost={externalId:string;platform:"x";authorId:string;username:string;displayName?:string;text:string;url:string;createdAt:Date;metrics:{likes:number;replies:number;reposts:number;quotes:number};author:{followers:number;verified:boolean}};
const STOP=new Set("a an and are as at be been being but by can could did do does for from had has have he her hers him his how i if in into is it its may me might my of on or our ours she should so than that the their theirs them they this those to too us was we were what when where which who why will with would you your yours people person someone something using use users want wants looking look find finds about around really just get gets got make makes need needs".split(" "));
const stem=(w:string)=>w.toLowerCase().replace(/[^a-z0-9]/g,"").replace(/(ing|edly|edly|ed|ies|s)$/,(m)=>m==="ies"?"y":"");
function terms(s:string){return [...new Set(s.split(/\s+/).map(stem).filter(w=>w.length>2&&!STOP.has(w)))];}
function relevance(text:string,description:string){const d=terms(description),t=terms(text);if(!description.trim()||!d.length)return {points:20,matched:[],coverage:0.5};const ts=new Set(t);const matched=d.filter(w=>ts.has(w));const coverage=matched.length/d.length;const phrases=(description.toLowerCase().match(/\b(?:struggl\w*|frustrat\w*|problem\w*|issue\w*|need\w*|looking for|recommend\w*|alternative\w*|switch\w*|buy\w*|pay\w*|deploy\w*|host\w*)\b/g)||[]);const phraseHits=phrases.filter(x=>text.toLowerCase().includes(x.replace(/\w\*$/,""))).length;return {points:Math.min(40,Math.round(coverage*34+Math.min(6,phraseHits*2))),matched:matched.slice(0,8),coverage:Number(coverage.toFixed(2))};}
export function scorePost(p:SocialPost,description="",now=new Date()){const age=Math.max(1,(+now-+p.createdAt)/60000),engagement=p.metrics.likes+p.metrics.reposts*2+p.metrics.quotes*2+p.metrics.replies,t=p.text.toLowerCase();const intent=/looking for|need (a|an|help)|budget|buy|pay for|how (do|can) i/.test(t)?"BUYING_INTENT":/recommend|alternative|what do you use|anyone use/.test(t)?"RECOMMENDATION_REQUEST":/expensive|frustrat|broken|hate|bill|stuck|fail|issue|problem|can't|cannot/.test(t)?"COMPLAINT":t.includes("?")?"QUESTION":/versus|competitor|switching from/.test(t)?"COMPETITOR_MENTION":/@\w+/.test(t)?"BRAND_MENTION":"GENERAL_DISCUSSION";const rel=relevance(p.text,description);const components={description_fit:rel.points,intent:["BUYING_INTENT","RECOMMENDATION_REQUEST"].includes(intent)?25:intent==="COMPLAINT"||intent==="QUESTION"?20:intent==="GENERAL_DISCUSSION"?5:12,freshness:Math.round(15*Math.exp(-age/180)),velocity:Math.round(Math.min(8,Math.log1p(engagement/age)*3)),saturation:Math.round(5/(1+p.metrics.replies/12)),reach:Math.round(Math.min(7,Math.log10(1+p.author.followers)*1.4))};return{score:Math.min(100,Object.values(components).reduce((a,b)=>a+b,0)),intent,components:{...components,description_terms_matched:rel.matched,description_coverage:rel.coverage}};}
