import { createHash } from "node:crypto";
import { validateQuery, type SocialPost } from "./domain";
export type SearchInput={query:string;cursor?:string|null;now?:Date;limit?:number};
export type SearchResult={posts:SocialPost[];cursor?:string};
export interface SocialSearchProvider{search(input:SearchInput):Promise<SearchResult>}
export class ProviderError extends Error{constructor(public code:string,public retryable:boolean,public retryAfter=60,public detail=code){super(code)}}
function detail(status:number,body:string,id?:string|null){return [`HTTP ${status}`,id?`request_id=${id}`:"",body.replace(/\s+/g," ").trim().slice(0,1200)].filter(Boolean).join(" | ")}
export class MockProvider implements SocialSearchProvider{async search({query,cursor,now=new Date(),limit=100}:SearchInput){validateQuery(query);if(query.includes("[error]"))throw new ProviderError("MOCK_PROVIDER_ERROR",true);const bucket=Math.floor(+now/60000),hash=createHash("sha256").update(query).digest("hex").slice(0,8),topic=query.match(/"([^"]+)"/)?.[1]||query.split(" ")[0];const posts=[0,1,2].map((i):SocialPost=>({externalId:`mock-${hash}-${bucket-i}`,platform:"x",authorId:`mock-author-${i}`,username:["maya_builds","samships","dev_lee"][i],displayName:["Maya Chen","Sam Rivera","Lee Park"][i],text:[`Looking for a better way to handle ${topic}. What would you recommend for a small SaaS?`,`Our ${topic} bill just doubled. Anyone found an alternative that actually works?`,`What do you use for ${topic}? Would love to hear from people shipping this week.`][i],url:"https://x.com/search?q="+encodeURIComponent(query),createdAt:new Date((bucket-i)*60000-15000),metrics:{likes:[31,8,2][i],replies:[3,12,1][i],reposts:[5,1,0][i],quotes:0},author:{followers:[4200,730,220][i],verified:false}}));return{posts:posts.slice(0,limit),cursor:String(bucket)}}}
export function normalizeX(p:any,users:any[]):SocialPost{const a=users.find(u=>u.id===p.author_id)||{};return{externalId:p.id,platform:"x",authorId:p.author_id,username:a.username||"unknown",displayName:a.name,text:p.text,url:`https://x.com/i/status/${p.id}`,createdAt:new Date(p.created_at),metrics:{likes:p.public_metrics?.like_count||0,replies:p.public_metrics?.reply_count||0,reposts:p.public_metrics?.retweet_count||0,quotes:p.public_metrics?.quote_count||0},author:{followers:a.public_metrics?.followers_count||0,verified:a.verified||false}}}
export class XProvider implements SocialSearchProvider{async search({query,cursor,limit=100}:SearchInput){validateQuery(query);if(!process.env.X_BEARER_TOKEN)throw new ProviderError("X_CREDENTIALS_MISSING",false,60,"X_BEARER_TOKEN is not configured on the worker");const capped=Math.max(10,Math.min(100,limit));const u=new URL("https://api.x.com/2/tweets/search/recent");u.searchParams.set("query",query);u.searchParams.set("max_results",String(capped));u.searchParams.set("tweet.fields","created_at,author_id,public_metrics");u.searchParams.set("expansions","author_id");u.searchParams.set("user.fields","username,name,public_metrics,verified");if(cursor)u.searchParams.set("since_id",cursor);let res:Response;try{res=await fetch(u,{headers:{Authorization:`Bearer ${process.env.X_BEARER_TOKEN}`},signal:AbortSignal.timeout(20000)})}catch(error){throw new ProviderError("X_NETWORK_ERROR",true,60,error instanceof Error?`${error.name}: ${error.message}`:String(error))}const raw=await res.text();if(!res.ok){const code=res.status===429?"X_RATE_LIMIT":res.status===401||res.status===403?"X_AUTH_REJECTED":res.status===400?"X_QUERY_INVALID":"X_UNAVAILABLE";throw new ProviderError(code,res.status===429||res.status>=500,60,detail(res.status,raw,res.headers.get("x-request-id")))}let body:any;try{body=raw?JSON.parse(raw):{}}catch{throw new ProviderError("X_INVALID_RESPONSE",true,60,`HTTP ${res.status} | Non-JSON response`)}if(body.errors?.length)throw new ProviderError("X_PARTIAL_RESPONSE",true,60,JSON.stringify(body.errors).slice(0,1200));return{posts:(body.data||[]).map((p:any)=>normalizeX(p,body.includes?.users||[])),cursor:body.meta?.newest_id||cursor||undefined}}
}
export function provider(name:string):SocialSearchProvider{if(name==="x")return new XProvider();if(name==="mock")return new MockProvider();throw new ProviderError("UNKNOWN_PROVIDER",false)}
